# Generated by Django 3.1.3 on 2021-05-12 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='matches',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('season', models.IntegerField()),
                ('city', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('team1', models.CharField(max_length=50)),
                ('team2', models.CharField(max_length=50)),
                ('toss_winner', models.CharField(max_length=50)),
                ('toss_decision', models.CharField(max_length=20)),
                ('result', models.CharField(max_length=20)),
                ('dl_applied', models.IntegerField()),
                ('winner', models.CharField(max_length=50)),
                ('win_by_runs', models.IntegerField()),
                ('win_by_wickets', models.IntegerField()),
                ('player_of_match', models.CharField(max_length=50)),
                ('venue', models.CharField(max_length=100)),
                ('umpire1', models.CharField(max_length=50)),
                ('umpire2', models.CharField(max_length=50)),
                ('umpire3', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
