# Generated by Django 3.1.3 on 2021-05-16 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipl_app', '0003_auto_20210512_2145'),
    ]

    operations = [
        migrations.CreateModel(
            name='temp_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form', models.IntegerField()),
            ],
        ),
    ]
